"""exo solve — diagnose + clarify + plan CLI."""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table
from rich.text import Text

from exo_runtime.solve import read_data_source, build_plan
from exo_runtime.solve.ranker import rank_issues
from exo_runtime.memory import MemoryStore

console = Console()


def _render_digest_overview(digest) -> None:
    console.print(Panel.fit(
        f"[bold cyan]exo solve[/bold cyan] — diagnosing [yellow]{digest.source_path}[/yellow]\n"
        f"Source type: [cyan]{digest.source_type}[/cyan]  ·  "
        f"Entities: [cyan]{digest.total_entities}[/cyan]  ·  "
        f"Issues extracted: [cyan]{len(digest.issues)}[/cyan]",
        border_style="cyan",
    ))
    if digest.summary_facts:
        facts = [f"{k}: {v}" for k, v in digest.summary_facts.items() if v is not None]
        if facts:
            console.print(Panel("\n".join(facts), title="Summary facts from data", border_style="dim"))


def _render_ranked_issues(digest, top_n: int) -> None:
    ranked = rank_issues(digest.issues, top_n=top_n)
    table = Table(title=f"Top {len(ranked)} issues by impact × actionability",
                  show_header=True, header_style="bold")
    table.add_column("#", style="dim", width=3)
    table.add_column("Issue", style="cyan")
    table.add_column("Type")
    table.add_column("Severity", justify="right")
    table.add_column("Composite", justify="right")
    table.add_column("Component")
    for i, (issue, composite) in enumerate(ranked, 1):
        sev_color = "red" if issue.severity >= 8 else "yellow" if issue.severity >= 5 else "white"
        table.add_row(
            str(i), issue.name, issue.issue_type,
            f"[{sev_color}]{issue.severity}[/{sev_color}]",
            str(composite),
            issue.component_type or "?",
        )
    console.print(table)


def _render_plan_to_markdown(plan, source_path: str, out_path: Path) -> None:
    lines = []
    lines.append(f"# Action plan — {source_path}")
    lines.append("")
    lines.append(f"_Generated by `exo solve` on {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")
    lines.append(f"**{plan.issues_evaluated}** total issues detected · **{plan.issues_in_plan}** ranked into this plan")
    lines.append("")
    for i, ip in enumerate(plan.plans, 1):
        lines.append(f"## {i}. {ip.issue.name} ({ip.issue.issue_type}, severity {ip.issue.severity})")
        lines.append("")
        if ip.issue.component_type:
            lines.append(f"- **Component type:** {ip.issue.component_type}")
        if ip.issue.evidence:
            lines.append(f"- **Evidence:** {', '.join(ip.issue.evidence[:5])}")
        if ip.issue.source_path:
            lines.append(f"- **Source:** `{ip.issue.source_path}`")
        lines.append("")
        lines.append(f"### Diagnosis")
        lines.append(f"{ip.diagnosis}")
        lines.append("")
        lines.append(f"### Hypotheses (ranked cheapest-first)")
        for h in ip.hypotheses:
            lines.append(f"- {h}")
        lines.append("")
        lines.append(f"### First action (needs your consent)")
        lines.append(f"**Step:** {ip.first_action.description}")
        if ip.first_action.command:
            lines.append(f"```")
            lines.append(ip.first_action.command)
            lines.append(f"```")
        if ip.first_action.verification:
            lines.append(f"**Verification:** {ip.first_action.verification}")
        if ip.first_action.rollback:
            lines.append(f"**Rollback:** {ip.first_action.rollback}")
        lines.append("")
        lines.append(f"### Clarifying questions before I propose more")
        for q in ip.clarifying_questions:
            lines.append(f"- {q}")
        lines.append("")
        if ip.recommended_capability:
            lines.append(f"### Tool recommendation")
            lines.append(f"If you'd consider a new tool for this, capability: **{ip.recommended_capability}**")
            lines.append(f"Run: `exo recommend {ip.recommended_capability}` for a scored shortlist.")
            lines.append("")
        lines.append("---")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def run(*, source_path: str, top_n: int = 5,
        out_dir: str | None = None, interactive: bool = True,
        invoke_recommend: bool = True) -> None:
    src = Path(source_path)
    digest = read_data_source(str(src))
    _render_digest_overview(digest)
    if not digest.issues:
        console.print("[yellow]No issues extracted from the data source. Nothing to plan.[/yellow]")
        return

    _render_ranked_issues(digest, top_n=top_n)

    plan = build_plan(digest, top_n=top_n)

    # Render plan inline
    console.print()
    console.print(Panel.fit("Per-issue diagnostic plan", border_style="cyan"))
    # Pull prior negative results once per session
    try:
        mem = MemoryStore()
    except Exception:
        mem = None

    for i, ip in enumerate(plan.plans, 1):
        console.print(f"\n[bold cyan]{i}. {ip.issue.name}[/bold cyan] · severity {ip.issue.severity} · {ip.issue.issue_type}")

        if mem is not None:
            regrets = mem.tried_and_failed(
                ip.issue.name, component_type=ip.issue.component_type, limit=5)
            priors = []
            # Also surface prior outcomes by component type
            if ip.issue.component_type:
                rows = mem.conn.execute("""
                    SELECT issue_name, confirmed_root_cause, fix_applied, recorded_at
                    FROM outcomes
                    WHERE component_type = ? AND issue_name != ?
                    ORDER BY recorded_at DESC LIMIT 3
                """, (ip.issue.component_type, ip.issue.name)).fetchall()
                priors = [dict(r) for r in rows]
            if regrets:
                console.print(f"  [bold yellow]⚠ Previously tried and didn't work:[/bold yellow]")
                for r in regrets[:3]:
                    console.print(f"    - {r['what_was_tried']}  [dim]({r['why_it_didnt_work']})[/dim]")
            if priors:
                console.print(f"  [bold green]Prior {ip.issue.component_type} outcomes:[/bold green]")
                for p in priors:
                    console.print(f"    - {p['issue_name']}: {p['confirmed_root_cause']}")

        console.print(f"  [italic]Diagnosis:[/italic] {ip.diagnosis[:300]}")
        console.print(f"  [italic]Hypotheses:[/italic]")
        for h in ip.hypotheses:
            console.print(f"    - {h}")
        console.print(f"  [italic]First action (needs your consent):[/italic] {ip.first_action.description}")
        if ip.first_action.command:
            console.print(f"    [yellow]{ip.first_action.command}[/yellow]")
        console.print(f"  [italic]Clarifying questions:[/italic]")
        for q in ip.clarifying_questions:
            console.print(f"    [dim]?[/dim] {q}")
        if ip.recommended_capability:
            console.print(
                f"  [italic]Tool suggestion:[/italic] [bold]{ip.recommended_capability}[/bold] "
                f"[dim](would call: exo recommend {ip.recommended_capability})[/dim]"
            )

    # Persist plan
    if out_dir is None:
        out_dir = str(src.parent / "exo-solve")
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    plan_file = out_path / f"plan-{src.stem}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.md"
    _render_plan_to_markdown(plan, src.name, plan_file)
    console.print(f"\n[dim]Plan written to: {plan_file}[/dim]")

    # Optionally invoke recommend for any capability suggestions
    if invoke_recommend:
        unique_caps = {ip.recommended_capability for ip in plan.plans if ip.recommended_capability}
        if unique_caps and interactive:
            for cap in unique_caps:
                console.print(f"\n[dim]Recommended capability detected: {cap}[/dim]")
                answer = Prompt.ask(
                    f"Run `exo recommend {cap}` now to score candidates?",
                    choices=["y", "n"], default="n",
                )
                if answer == "y":
                    from cli import recommend_cmd
                    recommend_cmd.run(capability=cap)


def main_solve(source_path: str, top_n: int = 5, out_dir: str | None = None,
               interactive: bool = True, no_recommend: bool = False) -> None:
    run(source_path=source_path, top_n=top_n, out_dir=out_dir,
        interactive=interactive, invoke_recommend=not no_recommend)
