"""Render a Placement + MigrationPlan as markdown."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .balancer import Placement, evaluate_placement, _usable_ram
from .fleet import Fleet
from .migration import MigrationPlan


def render_markdown(fleet: Fleet, placement: Placement,
                    migration: MigrationPlan) -> str:
    lines = []
    metrics = evaluate_placement(placement, fleet)
    lines.append(f"# Fleet rebalance plan — {fleet.name}")
    lines.append("")
    lines.append(f"_Generated by `exo plan` on {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")
    if fleet.description:
        lines.append(f"> {fleet.description}")
        lines.append("")
    lines.append(f"- **Strategy:** `{placement.strategy.value}`")
    lines.append(f"- **Workloads placed:** {metrics['workloads_placed']}/{metrics['workloads_total']}")
    lines.append(f"- **Constraint violations:** {metrics['violations']}")
    lines.append(f"- **RAM utilization (of usable):** min {metrics['util_min']}% · mean {metrics['util_mean']}% · max {metrics['util_max']}% · variance {metrics['variance']}")
    lines.append(f"- **Physical RAM ceiling:** max {metrics.get('physical_util_max', 0)}% (target <85%)")
    lines.append(f"- **CPU utilization:** mean {metrics.get('cpu_util_mean', 0)}% · max {metrics.get('cpu_util_max', 0)}%")
    if metrics.get('high_util_hosts'):
        lines.append(f"- ⚠ **High-utilization hosts** (>85% physical RAM): {', '.join(metrics['high_util_hosts'])}")
    lines.append("")
    lines.append("**Algorithm provenance:** Two-phase scheduling (Kubernetes-style filter→score), "
                 "First Fit Decreasing bin-packing, VMware DRS imbalance variance metric, "
                 "AWS 7 Rs migration framework. See [PRINCIPLES.md](../docs/PRINCIPLES.md).")
    lines.append("")

    # Per-host before/after
    lines.append("## Per-host before → after")
    lines.append("")
    lines.append("| Host | Current workloads | Current RAM | Target workloads | Target RAM | Usable RAM |")
    lines.append("|---|---|---|---|---|---|")
    for host in fleet.hosts:
        cur_wl = fleet.workloads_on(host.name)
        cur_ram = sum(w.ram_mb for w in cur_wl)
        new_ram = placement.host_ram_used.get(host.name, 0)
        new_count = placement.host_workload_count.get(host.name, 0)
        usable = _usable_ram(host)
        gpu_tag = " 🎮" if host.has_gpu else ""
        lines.append(
            f"| **{host.name}**{gpu_tag} | {len(cur_wl)} | {cur_ram} MB "
            f"({cur_ram*100//host.ram_mb}%) | {new_count} | {new_ram} MB "
            f"({new_ram*100//host.ram_mb}%) | {usable} MB |"
        )
    lines.append("")

    if placement.violations:
        lines.append("## ⚠ Constraint violations")
        lines.append("")
        for v in placement.violations:
            lines.append(f"- **{v.workload}** → `{v.target_host}` — {v.reason}")
        lines.append("")

    # Migration plan
    if not migration.waves:
        lines.append("## Migration plan")
        lines.append("")
        lines.append("No moves required — current placement is already balanced.")
        lines.append("")
    else:
        lines.append("## Migration plan (lowest blast-radius first)")
        lines.append("")
        for wave in migration.waves:
            lines.append(f"### Wave {wave.wave_n} · {wave.label}")
            lines.append("")
            for s in wave.steps:
                lines.append(
                    f"#### {s.workload.name} ({s.workload.workload_id}) · "
                    f"{s.from_host} → {s.to_host}"
                )
                lines.append("")
                lines.append(f"- **Risk:** {s.risk_score}/10 — {s.risk_reason}")
                lines.append(f"- **7 Rs strategy:** `{s.strategy}`")
                lines.append(f"- **Workload:** {s.workload.workload_type}, "
                            f"{s.workload.ram_mb} MB RAM, "
                            f"{s.workload.cpu_threads} CPU thread(s)"
                            + (f", needs GPU" if s.workload.needs_gpu else ""))
                if s.workload.notes:
                    lines.append(f"- **Notes:** {s.workload.notes}")
                lines.append("- **Proposed commands:**")
                lines.append("  ```")
                for c in s.proposed_commands:
                    lines.append(f"  {c}")
                lines.append("  ```")
                lines.append("- **Rollback:**")
                lines.append("  ```")
                for c in s.rollback_commands:
                    lines.append(f"  {c}")
                lines.append("  ```")
                lines.append("")

    if migration.no_op_workloads:
        lines.append("## Stays put")
        lines.append("")
        lines.append("These workloads are already on the right host:")
        lines.append("")
        for n in migration.no_op_workloads:
            lines.append(f"- {n}")
        lines.append("")

    return "\n".join(lines)


def write_plan(fleet: Fleet, placement: Placement, migration: MigrationPlan,
               out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = f"plan-{fleet.name}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.md"
    out_path = out_dir / fname
    out_path.write_text(render_markdown(fleet, placement, migration), encoding="utf-8")
    return out_path
